slotToName = [ "Head",
	       "Neck",
	       "Sholders",
	       "...", // shirt
	       "Chest",
	       "Waist",
	       "Legs",
	       "Feet",
	       "Wrists",
	       "Hands",
	       "Ring",
	       "Ring",
	       "Trinket",
	       "Trinket",
	       "Back",
	       "Main Hand",
	       "Off Hand",
	       "Ranged/Relic"
	     ];

reforgeIds = {
    bonusSpirit: {
	bonusDodgeRating: 113,
	bonusParryRating: 114,
	bonusHitRating: 115,
	bonusCritRating: 116,
	bonusHasteRating: 117,
	bonusExpertiseRating: 119,
	bonusMasteryRating: 119
    },
    bonusDodgeRating: {
	bonusSpirit: 120,
	bonusParryRating: 121,
	bonusHitRating: 122,
	bonusCritRating: 123,
	bonusHasteRating: 124,
	bonusExpertiseRating: 125,
	bonusMasteryRating: 126
    },
    bonusParryRating: {
	bonusSpirit: 127,
	bonusDodgeRating: 128,
	bonusHitRating: 129,
	bonusCritRating: 130,
	bonusHasteRating: 131,
	bonusExpertiseRating: 132,
	bonusMasteryRating: 133
    },
    bonusHitRating: {
	bonusSpirit: 134,
	bonusDodgeRating: 135,
	bonusParryRating: 136,
	bonusCritRating: 137,
	bonusHasteRating: 138,
	bonusExpertiseRating: 139,
	bonusMasteryRating: 140
    },
    bonusCritRating: {
	bonusSpirit: 141,
	bonusDodgeRating: 142,
	bonusParryRating: 143,
	bonusHitRating: 144,
	bonusHasteRating: 145,
	bonusExpertiseRating: 146,
	bonusMasteryRating: 147
    },
    bonusHasteRating: {
	bonusSpirit: 148,
	bonusDodgeRating: 149,
	bonusParryRating: 150,
	bonusHitRating: 151,
	bonusCritRating: 152,
	bonusExpertiseRating: 153,
	bonusMasteryRating: 154
    },
    bonusExpertiseRating: {
	bonusSpirit: 155,
	bonusDodgeRating: 156,
	bonusParryRating: 157,
	bonusHitRating: 158,
	bonusCritRating: 159,
	bonusHasteRating: 160,
	bonusMasteryRating: 161
    },
    bonusMasteryRating: {
	bonusSpirit: 162,
	bonusDodgeRating: 163,
	bonusParryRating: 164,
	bonusHitRating: 165,
	bonusCritRating: 166,
	bonusHasteRating: 167,
	bonusExpertiseRating: 168
    }
};
reforgeIdsReverse = {
    113: ["bonusSpirit", "bonusDodgeRating"],
    114: ["bonusSpirit", "bonusParryRating"],
    115: ["bonusSpirit", "bonusHitRating"],
    116: ["bonusSpirit", "bonusCritRating"],
    117: ["bonusSpirit", "bonusHasteRating"],
    118: ["bonusSpirit", "bonusExpertiseRating"],
    119: ["bonusSpirit", "bonusMasteryRating"],
    120: ["bonusDodgeRating", "bonusSpirit"],
    121: ["bonusDodgeRating", "bonusParryRating"],
    122: ["bonusDodgeRating", "bonusHitRating"],
    123: ["bonusDodgeRating", "bonusCritRating"],
    124: ["bonusDodgeRating", "bonusHasteRating"],
    125: ["bonusDodgeRating", "bonusExpertiseRating"],
    126: ["bonusDodgeRating", "bonusMasteryRating"],
    127: ["bonusParryRating", "bonusSpirit"],
    128: ["bonusParryRating", "bonusDodgeRating"],
    129: ["bonusParryRating", "bonusHitRating"],
    130: ["bonusParryRating", "bonusCritRating"],
    131: ["bonusParryRating", "bonusHasteRating"],
    132: ["bonusParryRating", "bonusExpertiseRating"],
    133: ["bonusParryRating", "bonusMasteryRating"],
    134: ["bonusHitRating", "bonusSpirit"],
    135: ["bonusHitRating", "bonusDodgeRating"],
    136: ["bonusHitRating", "bonusParryRating"],
    137: ["bonusHitRating", "bonusCritRating"],
    138: ["bonusHitRating", "bonusHasteRating"],
    139: ["bonusHitRating", "bonusExpertiseRating"],
    140: ["bonusHitRating", "bonusMasteryRating"],
    141: ["bonusCritRating", "bonusSpirit"],
    142: ["bonusCritRating", "bonusDodgeRating"],
    143: ["bonusCritRating", "bonusParryRating"],
    144: ["bonusCritRating", "bonusHitRating"],
    145: ["bonusCritRating", "bonusHasteRating"],
    146: ["bonusCritRating", "bonusExpertiseRating"],
    147: ["bonusCritRating", "bonusMasteryRating"],
    148: ["bonusHasteRating", "bonusSpirit"],
    149: ["bonusHasteRating", "bonusDodgeRating"],
    150: ["bonusHasteRating", "bonusParryRating"],
    151: ["bonusHasteRating", "bonusHitRating"],
    152: ["bonusHasteRating", "bonusCritRating"],
    153: ["bonusHasteRating", "bonusExpertiseRating"],
    154: ["bonusHasteRating", "bonusMasteryRating"],
    155: ["bonusExpertiseRating", "bonusSpirit"],
    156: ["bonusExpertiseRating", "bonusDodgeRating"],
    157: ["bonusExpertiseRating", "bonusParryRating"],
    158: ["bonusExpertiseRating", "bonusHitRating"],
    159: ["bonusExpertiseRating", "bonusCritRating"],
    160: ["bonusExpertiseRating", "bonusHasteRating"],
    161: ["bonusExpertiseRating", "bonusMasteryRating"],
    162: ["bonusMasteryRating", "bonusSpirit"],
    163: ["bonusMasteryRating", "bonusDodgeRating"],
    164: ["bonusMasteryRating", "bonusParryRating"],
    165: ["bonusMasteryRating", "bonusHitRating"],
    166: ["bonusMasteryRating", "bonusCritRating"],
    167: ["bonusMasteryRating", "bonusHasteRating"],
    168: ["bonusMasteryRating", "bonusExpertiseRating"]
};
